

version: '3'

services:
  mysql_db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_DATABASE=<dbname>
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
